### ISSUE TITLE
A couple of questions

### ISSUE THREAD

**Issue by RobertoMalatesta** [blackhole89/graphicdepictions#1]
Hi @blackhole89, compliments for this nice project!

I have 2 questions/suggestions on it:

Q1. instead of V8 did you consider the option of using Duktape as a Javascript engine?
Amongst pros are: 
- lighter, no dependencies (so it's easier to port it to _any_ architecture)
- Duktape can be compiled to emscripten as well so if you want to port it to the web using Emscripten/WASM you get a single code and no need to use the browser Javascript engine instead.

Q2. why don't you use a less viral license than GPL3 ?
GPL3 is, in terms of code reuse, a mix between Ebola and AIDS and taints any kind of mixing with libraries and components like other projects based on IMGUI or FreeType that are MIT/Apache/BSD or PD licensed.

Just my 2 EuroCents.

--R

**Comment by blackhole89** [comment]
Thanks, and thanks for the feedback!

Regarding Q1: I haven't actually heard of Duktape until now. I don't think V8 has any dependencies beyond the C and C++ standard library, either, but getting it to build on a variety of platforms was kind of a pain indeed. How does Duktape's performance compare to V8's (given that the latter's JIT was pretty widely hailed as a breakthrough when it first came out)? While most included examples at the moment are fairly simple, some applications I have in mind would certainly benefit from keeping the JavaScript part performant.

Regarding Q2: GPLv3 is compatible with MIT-style, Apache and BSD licenses as far as I know (in the sense that you can sublicense any code under the latter under GPLv3 without breaking the terms of the original license), and I'm totally in favour of re-releasing changes this project makes to libraries it imports under the original license. 

I can see how more permissive licenses would make sense if you are making a library and want as many people as possible to use it (especially since there are very few domains in which "take a source-available library, improve on it and sell it as a proprietary product" still makes economic sense), but it's not clear to me why one would want to use a non-viral license for a "terminal" project like this. It's hard to conceive of a scenario where someone would integrate the whole thing or significant parts of it in another project (and if you just replicate the way the main loop works or how it sets up the V8 callbacks or whatever in there may be of more general utility, it's very unlikely the GPL would transmit via that); on the other hand, I've actually seen several cases in the realm of academic software where a source-available program was displaced by an improved and more actively maintained closed-source version, which just seems like a bad scenario all around.

**Comment by RobertoMalatesta** [comment]
Hi @blackhole89 ,
Duktape is an interpreter-only very tiny javascript engine.
I use it in a financial application where I wanted to expose a C++ quant library (Quantlib) to some more agile scripting language, in this case TypeScript.
Its speed varies from 5x to 10x relating the V8 speed (maybe newer versions of Duktape are faster, and these are empirical numbers , no real benchmark).
Real plus is its size and embeddability and stability.

Regarding GPL3 (and strict copyleft licenses as well): I understand your point since I once was pro-GPLs ( still I am in some cases), but with time I came to realize that they don't protect the code, since if some bogus company or developer would want to pick it and write a closed app it's really difficult to enforce your rights.

The matter is complex, and no real optimal solution seem to exist.
If you want to preserve your source there's only a viable method: don't release it.

On the contrary, I've seen many companies offering something as GPL3 or Affero just to lure potential customers in, and lots of enterprises I worked in in the last years have a strong policy on sanitizing every possible GPL-licensed snippet out of their code base. 
That's not your case, given the size and the intention of the project.

On projects targeted to small developers the adoption of GPL licenses broke the things badly and lots of these projects suffered of stagnation because lots of good contributors did not agree.

As an in-topic example: let's suppose that someone takes a portion of your code, say the 3D spacial visualization of nodes, creates a component with it and wants to publish it as a IMGUI extension.
This extension would be forced to have a GPL3 license, no MIT, and anyone using  that would be forced to disclose the whole application that uses it.

I've seen lots of projects resulting in code license mess just because some developer overlooked the licensing issues and released as free (MIT/BSD) something mixed with non-free (GPL).

Just my 2 EuroCents.

Roberto

.
